NCIOCPL/drug-dictionary-app

babel.config.js
cypress/plugins/index.js
package-lock.json
package.json

Implementing the conditional instrumentation to prevent instrumentation when creating a production build.
Currently, instrumentation will be included when doing a build, significantly increasing the build size.

Conditional instrumentation for tests

---

src/components/atomic/az-list/AZList.jsx

(#31)Removed 'All' option from AZList

---

cypress/integration/TermPage.feature
cypress/integration/common/index.js
src/components/molecules/definitionitem/DefinitionItem.jsx
src/components/molecules/definitionitem/DefinitionItem.scss

Closes (#27)
Patient information button update

(#27) patient information button

---

cypress/integration/PrettyUrlRedirect.feature
cypress/integration/common/index.js
src/views/Definition/Definition.jsx
src/views/Definition/__tests__/Definition.PrettyURLRedirect.test.js
support/mock-data/drugdictionary/v1/Drugs/acenocoumarol.json

- Updated definition component to redirect to pretty url when ID is provided
- Added unit tests for prettyUrl redirect in definition
- Added integration test
Closes #13

(#13) Redirect to Pretty URL

---

cypress/integration/TermPage.feature
cypress/integration/common/index.js
package-lock.json
src/components/atomic/SynonymTable/synonym-table.scss
src/components/molecules/definitionitem/DefinitionItem.jsx
src/components/molecules/definitionitem/DefinitionItem.scss
src/components/molecules/definitionitem/__tests__/DefinitionItem.tests.js
src/views/Definition/Definition.jsx

Closes #28 
* Active Clinical Trials and Thesaurus links

(#28) Clinical Trials and Thesaurus links

---

cypress/integration/TermPage.feature
cypress/integration/common/index.js
src/components/molecules/definitionitem/DefinitionItem.jsx
src/components/molecules/definitionitem/__tests__/DefinitionItem.tests.js

- added click event handler in the definitonItem component
- added unit test
- added integration test
Closes #37

(#37) Analytics click event on PtInfo button

---

cypress/integration/AppAnalytics/ViewTermsByLetterAnalytics.feature
src/components/atomic/SynonymTable/synonym-table.jsx

Closes (#42)
* Fixes sorting for Synonym table

(#42) Synonym Table Order

---

src/components/atomic/SynonymTable/synonym-table.scss
src/components/molecules/definitionitem/DefinitionItem.scss
src/components/molecules/search-box/SearchBox.scss

Closes (#44)
Fixes CSS for IE 11

(#44) IE issues for Drug App

---

.pa11yci
cypress/integration/AppAnalytics/PageNotFoundAnalytics.feature
cypress/integration/PageNotFound.feature
cypress/integration/common/index.js
src/views/Definition/Definition.jsx
src/views/ErrorBoundary/ErrorBoundary.jsx
src/views/ErrorBoundary/PageNotFound.jsx

Closes (#15)
*Page Not Found 404

(#15) Page Not Found 404

---

src/components/molecules/search/Search.jsx

(#62) removed 'no results found' text

---

src/components/atomic/SynonymTable/synonym-table.jsx

(#59) sorted synonym table contents

---

src/views/Definition/Definition.jsx
src/views/Definition/__tests__/Definition.test.js
src/views/Terms/__tests__/terms.test.js
src/views/Terms/terms.jsx

-added effect to scroll to the top for definition and terms views
-unit tests
Closes #58

(#58) scroll position at the top of a page

---

src/views/SearchResults/SearchResults.jsx
src/views/SearchResults/__tests__/SearchResults.test.js

-added effect to scroll to the top of a page
- added unit test
Closes #74

(#74) added effect to scroll to the top of a page

---

src/styles/app.scss

(#51) Increase margin between h1 and intro text

---

cypress/integration/TermPage.feature
src/views/Definition/Definition.jsx

(#82) Title tag to include term name on definition page

---

cypress/integration/common/index.js
src/components/atomic/Autocomplete/Autocomplete.jsx
src/components/atomic/Autocomplete/Autocomplete.scss
support/mock-data/drugdictionary/v1/Drugs/acenocoumarol.json

Closes ( #78 )
* Add check for screen position and dropdown items for placement.

(#76) Fixes dropdown position based on screen

---

src/components/molecules/search/Search.jsx

Closes #39
* Removed term match filtering from autosuggest options

(#39) Autosuggest not displaying all suggestions

---

src/components/atomic/Autocomplete/Autocomplete.jsx
src/components/atomic/Autocomplete/__tests__/Autocomplete.tests.js
src/components/molecules/search/__tests__/Search.test.js

-updated unit tests
Closes #57

(#57) Updated autosuggest to not highlight first item

---

src/components/atomic/Autocomplete/Autocomplete.scss

Closes #80
* Added word wrap styling on autosuggest for IE

(#80) Horizontal scroll appears for autosuggest on IE

---

.editorconfig
.github/workflows/workflow.yml

Closes #93 .
Updated workflow.yml setting of env variables
Updated .editorconfig to properly handle yaml files

Fix for github actions env changeover 

---

cypress/integration/SearchResults.feature
src/views/ErrorBoundary/PageNotFound.jsx

- updated executeSearch on click event
- added integration test
Closes #91

(#91) Enable search from PageNotFound

---

package-lock.json
package.json

Closes #101
Updated axios version along with listed packages
npm update ini --depth 4
npm install --save-dev start-server-and-test@1.11.7
npm install axios@0.21.1
npm install --save-dev resolve-url-loader@3.1.2

Ticket#101 Axios version update to fix high severity security warning 

---

.github/workflows/workflow.yml
.pa11yci
cypress/integration/TermPage.feature
src/views/Definition/Definition.jsx

Also added in some workflow issues with Pa11y and updating the Github Actions.
Closes #107 
Closes #108 
Closes #109

(#107, #108, #109) Fix Definition Robots Issues

---

package-lock.json
package.json

* `package.json` and `package-loack.json` file updates after `npm audit fix`
Closes #117

(#117) Update npm security vulnerabilities

---

package-lock.json
package.json

(Closes #127)
- uninstalled node-sass
- installed sass

(#127) Change out node-sass for sass

---

config/webpack.config.js
config/webpackDevServer.config.js
package-lock.json
package.json
scripts/start.js

* Updated `react-dev-utils` from `10.2.1` to `12.0.1`
* Updated `webpack-dev-server` from `3.11.0` to `4.11.0`
* Resolved configuration issues from breaking changes
* Updated sass and related dependencies (css-loader, mini-css-extract-plugin, style-loader)
Closes https://github.com/NCIOCPL/drug-dictionary-app/issues/134

(#134) Resolve Webpack related vulnerabilities

---

package-lock.json

- Ran `npm audit fix` to upgrade packages
Closes #143

(#143) Upgrade loader-utils to version 2.0.4 or later

---

babel.config.js
config/webpack.config.js
cypress/e2e/common/MetaTags.js
cypress/e2e/common/analytics.js
cypress/e2e/common/beforeEach.js
cypress/e2e/common/index.js
jest-test-setup.js
merged.nyc.config.js
nyc.config.js
package.json
scripts/pre-merge-coverage.js
src/components/atomic/Autocomplete/Autocomplete.jsx
src/components/atomic/Autocomplete/__tests__/Autocomplete.tests.js
src/components/atomic/Radio/__tests__/Radio.tests.js
src/components/atomic/SynonymList/synonym-list.jsx
src/components/atomic/TextInput/__tests__/TextInput.test.js
src/components/molecules/SearchTermList/__tests__/search-term-list-test.js
src/components/molecules/TermList/__tests__/term-list-test.js
src/index.js
src/polyfills/index.js
src/serviceWorker.js
src/setupTests.js
src/views/Definition/__tests__/Definition.test.js
src/views/SearchResults/__tests__/SearchResults.unmockedRouter.js

**Setup Cypress Code Coverage**
- Added pre-merge script and merged coverage specific config
- Added reporting for full merged coverage
- Added text reporting after all integration tests
**Boosting Coverage to 80%**
- Updates coverage level to 80% across the board
- Removes test files from coverage
- Removes Create React App serviceWorker.js and setupTests.js from coverage
- Adds additional unit tests and makes minor modifications
Closes #113
Note: 3 commits. First to setup the code coverage. The second to update code in order to boost the coverage percentage. The third for Cypress lint fixes.

(#113) Setup Cypress Code Coverage and Merge with Jest
